services:
    security.acl.permission.map:
      class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

    registration.user_creation:
        class: BlogBundle\EventListener\UserCreationListener
        arguments: [ "@doctrine.orm.entity_manager"  ]
        tags:
           - { name: kernel.event_subscriber, alias: registration_listener }


    admin.post:
        class: BlogBundle\Admin\PostAdmin
        arguments: [~, BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post, group: "Postes" }



    admin.category:
        class: BlogBundle\Admin\CategoryAdmin
        arguments: [~, BlogBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category, group: "Categories" }
    admin.comment:
        class: BlogBundle\Admin\CommentAdmin
        arguments: [~, BlogBundle\Entity\Comment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Comment, group: "Postes" }
    twigdate.listener.request:
        class: BlogBundle\Services\CurrentUserManager
        arguments:
            - "@=service('security.token_storage').getToken().getUser()"
    #event_listener.comment:
        #class: BlogBundle\EventListener\CommentListener
        #arguments: ["@security.token_storage"]
        #tags:
           # - { name: doctrine.event_listener, event: prePost }

