<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;


/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;






    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function __construct()
    {
        parent::__construct();

        // Add role default
        $this->addRole("ROLE_UTILISATEUR");


    }


    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $user_comments;


    /**
     * Add userComment
     *
     * @param \BlogBundle\Entity\Comment $userComment
     *
     * @return User
     */
    public function addUserComment(\BlogBundle\Entity\Comment $userComment)
    {
        $this->user_comments[] = $userComment;

        return $this;
    }

    /**
     * Remove userComment
     *
     * @param \BlogBundle\Entity\Comment $userComment
     */
    public function removeUserComment(\BlogBundle\Entity\Comment $userComment)
    {
        $this->user_comments->removeElement($userComment);
    }

    /**
     * Get userComments
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUserComments()
    {
        return $this->user_comments;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $user_posts;


    /**
     * Add userPost
     *
     * @param \BlogBundle\Entity\Post $userPost
     *
     * @return User
     */
    public function addUserPost(\BlogBundle\Entity\Post $userPost)
    {
        $this->user_posts[] = $userPost;

        return $this;
    }

    /**
     * Remove userPost
     *
     * @param \BlogBundle\Entity\Post $userPost
     */
    public function removeUserPost(\BlogBundle\Entity\Post $userPost)
    {
        $this->user_posts->removeElement($userPost);
    }

    /**
     * Get userPosts
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUserPosts()
    {
        return $this->user_posts;
    }
}
